/** @type {import("stylelint").Config} */
const stylelint = {
    rules: {
        "no-descending-specificity": true,
        "declaration-block-no-duplicate-properties": true,
        "font-family-no-duplicate-names": true,
        "keyframe-block-no-duplicate-selectors": true,
        "no-duplicate-at-import-rules": true,
        "no-duplicate-selectors": true,
        "block-no-empty": true,
        "comment-no-empty": true,
        "no-empty-source": true,
        "color-no-invalid-hex": true,
        "function-calc-no-unspaced-operator": true,
        "keyframe-declaration-no-important": true,
        "media-query-no-invalid": true,
        "named-grid-areas-no-invalid": true,
        "no-invalid-double-slash-comments": true,
        "no-invalid-position-at-import-rule": true,
        "string-no-newline": true,
        "no-irregular-whitespace": true,
        "custom-property-no-missing-var-function": true,
        "font-family-no-missing-generic-family-keyword": true,
        "function-linear-gradient-no-nonstandard-direction": true,
        "declaration-block-no-shorthand-property-overrides": true,
        "selector-anb-no-unmatchable": true,
        "annotation-no-unknown": true,
        "at-rule-no-unknown": true,
        "declaration-property-value-no-unknown": true,
        "function-no-unknown": true,
        "media-feature-name-no-unknown": true,
        "media-feature-name-value-no-unknown": true,
        "no-unknown-animations": true,
        "no-unknown-custom-media": true,
        "no-unknown-custom-properties": true,
        "property-no-unknown": true,
        "selector-pseudo-class-no-unknown": true,
        "selector-pseudo-element-no-unknown": true,
        "selector-type-no-unknown": true,
        "unit-no-unknown": true,
        "at-rule-no-vendor-prefix": true,
        "color-hex-alpha": "never",
        "color-named": "never",
        "declaration-no-important": true,
        "function-url-no-scheme-relative": true,
        "length-zero-no-unit": true,
        "media-feature-name-no-vendor-prefix": true,
        "property-no-vendor-prefix": true,
        "selector-no-vendor-prefix": true,
        "unit-allowed-list": ["px", "rem", "%"],
        "value-no-vendor-prefix": true,
        "function-name-case": "lower",
        "selector-type-case": "lower",
        "value-keyword-case": "lower",
        "at-rule-empty-line-before": [
            "always",
            { ignore: ["first-nested", "after-comment"] },
        ],
        "comment-empty-line-before": ["always", { except: ["first-nested"] }],
        "custom-property-empty-line-before": "never",
        "rule-empty-line-before": [
            "always",
            {
                except: ["after-single-line-comment"],
                ignore: ["first-nested", "after-comment"],
            },
        ],
        "number-max-precision": 3,
        "alpha-value-notation": "percentage",
        "color-function-notation": "modern",
        "color-hex-length": "long",
        "font-weight-notation": "numeric",
        "hue-degree-notation": "angle",
        "import-notation": "string",
        "keyframe-selector-notation": "percentage",
        "lightness-notation": "percentage",
        "media-feature-range-notation": "prefix",
        "selector-not-notation": "complex",
        "selector-pseudo-element-colon-notation": "single",
        "font-family-name-quotes": "always-where-required",
        "function-url-quotes": "always",
        "selector-attribute-quotes": "always",
        "shorthand-property-no-redundant-values": true,
        "declaration-block-no-redundant-longhand-properties": [
            true,
            { ignoreShorthands: "grid-template" },
        ],
    },
}

module.exports = {
    stylelint,
}
