/** @type {import("@types/eslint").ESLint.ConfigData} */
module.exports = {
    plugins: ["import-x"],
    rules: {
        "import-x/export": "error",
        "import-x/no-deprecated": "error",
        "import-x/no-empty-named-blocks": "error",
        "import-x/no-extraneous-dependencies": "error",
        "import-x/no-mutable-exports": "error",
        "import-x/no-named-as-default": "error",
        "import-x/no-named-as-default-member": "error",
        "import-x/default": "error",
        "import-x/named": "error",
        "import-x/namespace": "error",
        "import-x/no-absolute-path": "error",
        "import-x/no-cycle": "error",
        "import-x/no-dynamic-require": "error",
        "import-x/no-relative-packages": "error",
        "import-x/no-self-import": "error",
        "import-x/no-useless-path-segments": "error",
        "import-x/exports-last": "error",
        "import-x/first": "error",
        "import-x/newline-after-import": "error",
        "import-x/no-anonymous-default-export": "error",
        "import-x/no-duplicates": "error",
        "import-x/no-named-default": "error",
        "import-x/order": "error",
    },
}
