import plugin from "eslint-plugin-unicorn"

/** @type {import("@eslint/config-helpers").Config} */
export const unicorn = {
    plugins: {
        unicorn: plugin,
    },
    rules: {
        "unicorn/catch-error-name": "error",
        "unicorn/consistent-date-clone": "error",
        "unicorn/consistent-destructuring": "error",
        "unicorn/consistent-empty-array-spread": "error",
        "unicorn/consistent-existence-index-check": "error",
        "unicorn/consistent-function-scoping": "error",
        "unicorn/consistent-json-file-read": "error",
        "unicorn/dom-node-dataset": "error",
        "unicorn/empty-brace-spaces": "error",
        "unicorn/error-message": "error",
        "unicorn/escape-case": "error",
        "unicorn/explicit-length-check": "error",
        "unicorn/filename-case": [
            "error",
            {
                cases: {
                    camelCase: true,
                    kebabCase: true,
                    pascalCase: true,
                },
                checkDirectories: false,
            },
        ],
        "unicorn/isolated-functions": "error",
        "unicorn/name-replacements": [
            "error",
            {
                ignore: [
                    "utils",
                    "Utils",
                    "Arg",
                    "Args",
                    "Param",
                    "Params",
                    "Prev",
                    "Prop",
                    "Props",
                    "Ref",
                    "Refs",
                    "arg",
                    "args",
                    "env",
                    "param",
                    "params",
                    "prev",
                    "prop",
                    "props",
                    "ref",
                    "refs",
                ],
            },
        ],
        "unicorn/new-for-builtins": "error",
        "unicorn/no-abusive-eslint-disable": "error",
        "unicorn/no-accessor-recursion": "error",
        "unicorn/no-anonymous-default-export": "error",
        "unicorn/no-array-callback-reference": "error",
        "unicorn/no-array-fill-with-reference-type": "error",
        "unicorn/no-array-from-fill": "error",
        "unicorn/no-array-method-this-argument": "error",
        "unicorn/no-array-reduce": "error",
        "unicorn/no-array-reverse": "error",
        "unicorn/no-array-sort-for-min-max": "error",
        "unicorn/no-array-splice": "error",
        "unicorn/no-await-expression-member": "error",
        "unicorn/no-await-in-promise-methods": "error",
        "unicorn/no-chained-comparison": "error",
        "unicorn/no-console-spaces": "error",
        "unicorn/no-constant-zero-expression": "error",
        "unicorn/no-document-cookie": "error",
        "unicorn/no-double-comparison": "error",
        "unicorn/no-duplicate-logical-operands": "error",
        "unicorn/no-duplicate-set-values": "error",
        "unicorn/no-empty-file": "error",
        "unicorn/no-for-loop": "error",
        "unicorn/no-immediate-mutation": "error",
        "unicorn/no-impossible-length-comparison": "error",
        "unicorn/no-instanceof-builtins": "error",
        "unicorn/no-invalid-fetch-options": "error",
        "unicorn/no-invalid-remove-event-listener": "error",
        "unicorn/no-lonely-if": "error",
        "unicorn/no-magic-array-flat-depth": "error",
        "unicorn/no-mismatched-map-key": "error",
        "unicorn/no-named-default": "error",
        "unicorn/no-negation-in-equality-check": "error",
        "unicorn/no-new-array": "error",
        "unicorn/no-new-buffer": "error",
        "unicorn/no-object-as-default-parameter": "error",
        "unicorn/no-object-methods-with-collections": "error",
        "unicorn/no-process-exit": "error",
        "unicorn/no-return-array-push": "error",
        "unicorn/no-single-promise-in-promise-methods": "error",
        "unicorn/no-static-only-class": "error",
        "unicorn/no-thenable": "error",
        "unicorn/no-this-assignment": "error",
        "unicorn/no-typeof-undefined": "error",
        "unicorn/no-unnecessary-array-flat-depth": "error",
        "unicorn/no-unnecessary-array-splice-count": "error",
        "unicorn/no-unnecessary-await": "error",
        "unicorn/no-unnecessary-nested-ternary": "error",
        "unicorn/no-unnecessary-polyfills": "error",
        "unicorn/no-unnecessary-slice-end": "error",
        "unicorn/no-unreadable-array-destructuring": "error",
        "unicorn/no-unreadable-iife": "error",
        "unicorn/no-unsafe-buffer-conversion": "error",
        "unicorn/no-unsafe-dom-html": "error",
        "unicorn/no-unsafe-property-key": "error",
        "unicorn/no-unsafe-string-replacement": "error",
        "unicorn/no-unused-array-method-return": "error",
        "unicorn/no-unused-properties": "error",
        "unicorn/no-useless-collection-argument": "error",
        "unicorn/no-useless-continue": "error",
        "unicorn/no-useless-delete-check": "error",
        "unicorn/no-useless-else": "error",
        "unicorn/no-useless-error-capture-stack-trace": "error",
        "unicorn/no-useless-fallback-in-spread": "error",
        "unicorn/no-useless-length-check": "error",
        "unicorn/no-useless-promise-resolve-reject": "error",
        "unicorn/no-useless-switch-case": "error",
        "unicorn/no-useless-undefined": "error",
        "unicorn/no-zero-fractions": "error",
        "unicorn/number-literal-case": "error",
        "unicorn/numeric-separators-style": "error",
        "unicorn/prefer-abort-signal-any": "error",
        "unicorn/prefer-abort-signal-timeout": "error",
        "unicorn/prefer-aggregate-error": "error",
        "unicorn/prefer-array-find": "error",
        "unicorn/prefer-array-flat": "error",
        "unicorn/prefer-array-flat-map": "error",
        "unicorn/prefer-array-from-async": "error",
        "unicorn/prefer-array-from-map": "error",
        "unicorn/prefer-array-from-range": "error",
        "unicorn/prefer-array-index-of": "error",
        "unicorn/prefer-array-last-methods": "error",
        "unicorn/prefer-array-slice": "error",
        "unicorn/prefer-array-some": "error",
        "unicorn/prefer-at": "error",
        "unicorn/prefer-blob-reading-methods": "error",
        "unicorn/prefer-code-point": "error",
        "unicorn/prefer-date-now": "error",
        "unicorn/prefer-default-parameters": "error",
        "unicorn/prefer-dispose": "error",
        "unicorn/prefer-dom-node-append": "error",
        "unicorn/prefer-dom-node-remove": "error",
        "unicorn/prefer-dom-node-text-content": "error",
        "unicorn/prefer-error-is-error": "error",
        "unicorn/prefer-event-target": "error",
        "unicorn/prefer-export-from": ["error", { checkUsedVariables: false }],
        "unicorn/prefer-flat-math-min-max": "error",
        "unicorn/prefer-get-or-insert-computed": "error",
        "unicorn/prefer-global-number-constants": "error",
        "unicorn/prefer-group-by": "error",
        "unicorn/prefer-https": "error",
        "unicorn/prefer-import-meta-properties": "error",
        "unicorn/prefer-includes": "error",
        "unicorn/prefer-iterator-concat": "error",
        "unicorn/prefer-iterator-to-array": "error",
        "unicorn/prefer-keyboard-event-key": "error",
        "unicorn/prefer-logical-operator-over-ternary": "error",
        "unicorn/prefer-math-abs": "error",
        "unicorn/prefer-math-constants": "error",
        "unicorn/prefer-math-min-max": "error",
        "unicorn/prefer-math-trunc": "error",
        "unicorn/prefer-modern-dom-apis": "error",
        "unicorn/prefer-modern-math-apis": "error",
        "unicorn/prefer-negative-index": "error",
        "unicorn/prefer-node-protocol": "error",
        "unicorn/prefer-number-coercion": "error",
        "unicorn/prefer-number-is-safe-integer": "error",
        "unicorn/prefer-number-properties": "error",
        "unicorn/prefer-object-from-entries": "error",
        "unicorn/prefer-optional-catch-binding": "error",
        "unicorn/prefer-promise-try": "error",
        "unicorn/prefer-promise-with-resolvers": "error",
        "unicorn/prefer-prototype-methods": "error",
        "unicorn/prefer-query-selector": "error",
        "unicorn/prefer-queue-microtask": "error",
        "unicorn/prefer-reflect-apply": "error",
        "unicorn/prefer-regexp-test": "error",
        "unicorn/prefer-response-static-json": "error",
        "unicorn/prefer-set-has": "error",
        "unicorn/prefer-set-size": "error",
        "unicorn/prefer-single-call": "error",
        "unicorn/prefer-string-match-all": "error",
        "unicorn/prefer-string-pad-start-end": "error",
        "unicorn/prefer-string-repeat": "error",
        "unicorn/prefer-string-replace-all": "error",
        "unicorn/prefer-string-slice": "error",
        "unicorn/prefer-string-starts-ends-with": "error",
        "unicorn/prefer-string-trim-start-end": "error",
        "unicorn/prefer-structured-clone": "error",
        "unicorn/prefer-switch": "error",
        "unicorn/prefer-ternary": "error",
        "unicorn/prefer-type-error": "error",
        "unicorn/prefer-url-can-parse": "error",
        "unicorn/prefer-url-href": "error",
        "unicorn/relative-url-style": ["error", "always"],
        "unicorn/require-array-join-separator": "error",
        "unicorn/require-array-sort-compare": "error",
        "unicorn/require-number-to-fixed-digits-argument": "error",
        "unicorn/require-post-message-target-origin": "error",
        "unicorn/switch-case-braces": ["error", "always"],
        "unicorn/template-indent": [
            "warn",
            {
                indent: 4,
            },
        ],
        "unicorn/text-encoding-identifier-case": "error",
        "unicorn/throw-new-error": "error",
    },
}
